default: &default
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USERNAME'] || nil %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: unicode

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'eco_run_club_development' %>

test:
  <<: *default
  database: eco_run_club_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
